function(print_compile_values)
    message("* CMAKE_C_FLAGS : ${CMAKE_C_FLAGS}")
    message("* CMAKE_CXX_FLAGS : ${CMAKE_CXX_FLAGS}")
    message("* CMAKE_EXE_LINKER_FLAGS : ${CMAKE_EXE_LINKER_FLAGS}")
    message("* CMAKE_SOURCE_DIR : ${CMAKE_SOURCE_DIR}")
    message("* CMAKE_BINARY_DIR : ${CMAKE_BINARY_DIR}")
    message("* CFLAGS : ${CFLAGS}")
    message("* CPPFLAGS : ${CPPFLAGS}")
    message("* LDFLAGS : ${LDFLAGS}")
 endfunction()

function(print_project_values)
    message("* PROJECT_SOURCE_DIR : ${PROJECT_SOURCE_DIR}")
    message("* PROJECT_BINARY_DIR : ${PROJECT_BINARY_DIR}")
endfunction()

# http://zashikiro.hateblo.jp/entry/2014/05/17/001314
function(print_all_values)
    message(STATUS "*** dump start cmake variables ***")
    get_cmake_property(_variableNames VARIABLES)
    foreach(_variableName ${_variableNames})
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
    message(STATUS "*** dump end ***")
endfunction()